### ISSUE TITLE
Testing Armorcoat_b1_mac 

### ISSUE THREAD

**Issue by AndreaMonzini** [armory3d/material_editor#2]
Hello,

i'm testing it on old iMac but i will test on other systems soon:
i try to run the app with double click on iMac® late 2009 OSX® 10.12.5 but i see this message:
“Armorcoat” is damaged and can’t be opened. 

If i open Krom from the terminal it starts!

`imacs-iMac:~ imac$ /Users/imac/Downloads/Armorcoat.app/Contents/MacOS/Krom
deviceBufferSize = 4096

mSampleRate = 44100

mFormatFlags = 00000009

mBytesPerPacket = 8

mFramesPerPacket = 1

mChannelsPerFrame = 2

mBytesPerFrame = 8

mBitsPerChannel = 32

`

During the test i see some graphic glitches ( GPU AMD 4670 )
![coat](https://user-images.githubusercontent.com/12413409/29995233-10b66f20-8fe5-11e7-9fe6-49df2d883426.png)

**Comment by luboslenco** [comment]
Migrated this repo functionality to the armorpaint. :)
